### PR TITLE
Online viterbi decoder pull request

### PR DESCRIPTION
**Pull request by serenchoe**
Hello,

I happended to find your code while reviewing sramek's paper.
I tried your code and found two following issues. 
   1) online viterbi decoder result is not same with standard viterbi decoder
   2) some memory leak
   3) pretty print to show online viterbi decode result and standard viterbi decode result at the same time

I think I fixed those issue, please review my changes

Thanks

### CODE REVIEW

**Comment by franciscoambrosio** [comment]
Hello serenchoe,

I am glad you are willing to contribute and I am aware there was a leak because the online algorithm stopped working after some simulation time.
According to my research there is no other code in C openly available of the online algorithm.
I will review on the next days.

Thank you

**Review by franciscoambrosio — APPROVED** [review]
It solved the problems you mentioned but there is still one more problem that I already had. If you set T (#of time instances) larger than 500, both the standard and online versions start to produce just zeros in the end. Do you have any idea of why it happens?

**Comment by serenchoe** [comment]
I don't understand why this happens either. But when I tried very big T in other standard viterbi decoder, which also show same situation. So I'm not sure this is a bug or not.

**Comment by serenchoe** [comment]
Maybe it's because probability column becomes all zero column if T is too big. In that case index column also contains all zero values and it make zero sequences in the end. This is my guess and need more investigation.

**Comment by franciscoambrosio** [comment]
This is reasonable. If you look at the other paper (A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition) they say that to avoid numerical problems it is advised to use the log of the probabilities instead of the probabilities themselves. Then the probabilities multiplications become the sum of their logs.

**Pull request merged**
